from typing import Protocol
from uuid import UUID

from app.domain.entities.exam import Exam


class IExamRepository(Protocol):
    async def save(self, exam: Exam) -> None: ...
    async def update(self, exam: Exam) -> None: ...
    async def delete(self, exam_id: UUID) -> None: ...
    async def find_by_id(self, exam_id: UUID) -> Exam | None: ...
    async def find_all(self) -> list[Exam]: ...
