"""Add number, confidence, and source to Question

Revision ID: b2dc050d1685
Revises: e0678cb7be9e
Create Date: 2026-04-17 14:29:23.397630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b2dc050d1685'
down_revision: Union[str, Sequence[str], None] = 'e0678cb7be9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('question', sa.Column('source', sa.String(length=50), nullable=False))
    
    # Check if indexes exist before dropping to avoid errors if already dropped
    # However, standard Alembic auto-gen doesn't check. 
    # We'll keep it simple and just do the add_columns first as they are the main blockers.
    # op.drop_index(op.f('ix_question_area'), table_name='question')
    # op.drop_index(op.f('ix_question_exam_id'), table_name='question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_question_exam_id'), 'question', ['exam_id'], unique=False)
    # op.create_index(op.f('ix_question_area'), 'question', ['area'], unique=False)
    op.drop_column('question', 'source')
    op.drop_column('question', 'confidence')
    op.drop_column('question', 'number')
    # ### end Alembic commands ###
