"""add exam type and color

Revision ID: dbab6171db27
Revises: b2dc050d1685
Create Date: 2026-04-17 15:24:23.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbab6171db27'
down_revision: Union[str, Sequence[str], None] = 'b2dc050d1685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_type', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('exam', sa.Column('color', sa.String(length=30), nullable=False, server_default='BRANCA'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'color')
    op.drop_column('exam', 'exam_type')
    # ### end Alembic commands ###
