from typing import Protocol
from uuid import UUID

from app.domain.entities.question import Question
from app.domain.enums.law_area import LawArea


class IQuestionRepository(Protocol):
    async def save(self, question: Question) -> None: ...
    async def update(self, question: Question) -> None: ...
    async def delete(self, question_id: UUID) -> None: ...
    async def delete_all_by_exam_id(self, exam_id: UUID) -> int: ...
    async def find_by_id(self, question_id: UUID) -> Question | None: ...
    async def find_by_ids(self, question_ids: list[UUID]) -> list[Question]: ...
    async def find_all_by_exam_id(self, exam_id: UUID) -> list[Question]: ...
    async def find_by_area(
        self, area: LawArea, limit: int = 5
    ) -> list[Question]: ...
    async def find_one_by_exam_id_at_index(
        self, exam_id: UUID, index: int
    ) -> Question | None: ...
    async def count_by_exam_id(self, exam_id: UUID) -> int: ...
    async def find_by_embedding_similarity(
        self,
        query_vector: list[float],
        limit: int,
        exam_id: UUID | None = None,
    ) -> list[tuple[Question, float]]: ...
