from typing import Protocol
from uuid import UUID

from app.domain.entities.question import Question


class IQuestionRepository(Protocol):
    async def save(self, question: Question) -> None: ...
    async def update(self, question: Question) -> None: ...
    async def delete(self, question_id: UUID) -> None: ...
    async def delete_all_by_exam_id(self, exam_id: UUID) -> int: ...
    async def find_by_id(self, question_id: UUID) -> Question | None: ...
    async def find_all_by_exam_id(self, exam_id: UUID) -> list[Question]: ...
    async def find_one_by_exam_id_at_index(
        self, exam_id: UUID, index: int
    ) -> Question | None: ...
    async def count_by_exam_id(self, exam_id: UUID) -> int: ...
