from typing import Protocol
from uuid import UUID
from app.domain.entities.study import Study
from app.domain.enums.law_area import LawArea

class IStudyRepository(Protocol):
    async def save(self, study: Study) -> None: ...
    async def update(self, study: Study) -> None: ...
    async def find_by_user_and_area(self, user_id: UUID, area: LawArea) -> Study | None: ...
    async def find_all_by_user_id(self, user_id: UUID) -> list[Study]: ...
    async def find_due_by_user_id(self, user_id: UUID) -> list[Study]: ...
