"""add server_default to priority_score

Revision ID: 3b4c662025b9
Revises: f3402f7001b6
Create Date: 2026-04-23 18:18:16.714854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4c662025b9'
down_revision: Union[str, Sequence[str], None] = 'f3402f7001b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_study_note_next_review'), table_name='study_note')
    op.drop_index(op.f('idx_study_question_next_review'), table_name='study_question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_study_question_next_review'), 'study_question', [sa.literal_column("(review_progress ->> 'next_review_date'::text)")], unique=False)
    op.create_index(op.f('idx_study_note_next_review'), 'study_note', [sa.literal_column("(review_progress ->> 'next_review_date'::text)")], unique=False)
    # ### end Alembic commands ###
