"""add priority_score to question table

Revision ID: 4b5184db3a63
Revises: 34aed8106246
Create Date: 2026-04-23 18:03:49.891520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5184db3a63'
down_revision: Union[str, Sequence[str], None] = '34aed8106246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Adicionar como nullable inicialmente
    op.add_column('question', sa.Column('priority_score', sa.Float(), nullable=True))
    
    # 2. Preencher com valor padrão (0.0) para linhas existentes
    op.execute("UPDATE question SET priority_score = 0.0")
    
    # 3. Alterar para NOT NULL
    op.alter_column('question', 'priority_score', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'priority_score')
    # ### end Alembic commands ###
