"""create_study_table

Revision ID: 561f86ef3dc3
Revises: 072d78397f6c
Create Date: 2026-04-23 10:28:17.545198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '561f86ef3dc3'
down_revision: Union[str, Sequence[str], None] = '072d78397f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_progress', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area', name='uq_user_area_study')
    )
    op.drop_index(op.f('ix_question_area'), table_name='question')
    op.drop_index(op.f('ix_question_exam_id'), table_name='question')
    op.drop_index(op.f('question_embedding_hnsw_idx'), table_name='question', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('study_note_embedding_hnsw_idx'), table_name='study_note', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('study_note_embedding_hnsw_idx'), 'study_note', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('question_embedding_hnsw_idx'), 'question', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_question_exam_id'), 'question', ['exam_id'], unique=False)
    op.create_index(op.f('ix_question_area'), 'question', ['area'], unique=False)
    op.drop_table('study')
    # ### end Alembic commands ###
