"""ajustes na estrutura do banco

Revision ID: a9cd382310e8
Revises: c9a4d1f3b82e
Create Date: 2026-04-22 11:03:40.221175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9cd382310e8'
down_revision: Union[str, Sequence[str], None] = 'c9a4d1f3b82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_area'), table_name='question')
    op.drop_index(op.f('ix_question_exam_id'), table_name='question')
    op.drop_index(op.f('question_embedding_hnsw_idx'), table_name='question', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('question', 'embedding')
    op.drop_index(op.f('study_note_embedding_hnsw_idx'), table_name='study_note', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('study_note_embedding_hnsw_idx'), 'study_note', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('question', sa.Column('embedding', postgresql.HALFVEC(dim=3072), autoincrement=False, nullable=True))
    op.create_index(op.f('question_embedding_hnsw_idx'), 'question', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_question_exam_id'), 'question', ['exam_id'], unique=False)
    op.create_index(op.f('ix_question_area'), 'question', ['area'], unique=False)
    # ### end Alembic commands ###
