"""ajustes na estrutura do banco

Revision ID: a9cd382310e8
Revises: a2b3c4d5e6f7
Create Date: 2026-04-22 11:03:40.221175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import HALFVEC

# revision identifiers, used by Alembic.
revision: str = 'a9cd382310e8'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed: op.drop_index(op.f('ix_question_area'), table_name='question')
    # Removed: op.drop_index(op.f('ix_question_exam_id'), table_name='question')
    # Removed: op.drop_column('question', 'embedding')
    # Keeping embedding column and its index as they are needed
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration now only has a pass statement, so downgrade is also a pass
    # ### end Alembic commands ###
    pass
