"""Add number, confidence, and source to Question

Revision ID: b2dc050d1685
Revises: e0678cb7be9e
Create Date: 2026-04-17 14:29:23.397630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2dc050d1685'
down_revision: Union[str, Sequence[str], None] = 'e0678cb7be9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_exam_stats',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('edition', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('questions_by_area', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('exam_id'),
    info={'is_view': True}
    )
    op.create_table('v_question_detail',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.String(length=1500), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('correct', sa.String(length=1), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('exam_name', sa.String(length=150), nullable=False),
    sa.Column('exam_edition', sa.Integer(), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('exam_board', sa.String(length=100), nullable=False),
    sa.Column('first_phase_date', sa.Date(), nullable=True),
    sa.Column('second_phase_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('question_id'),
    info={'is_view': True}
    )
    op.add_column('question', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('question', sa.Column('source', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_question_area'), table_name='question')
    op.drop_index(op.f('ix_question_exam_id'), table_name='question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_question_exam_id'), 'question', ['exam_id'], unique=False)
    op.create_index(op.f('ix_question_area'), 'question', ['area'], unique=False)
    op.drop_column('question', 'source')
    op.drop_column('question', 'confidence')
    op.drop_column('question', 'number')
    op.drop_table('v_question_detail')
    op.drop_table('v_exam_stats')
    # ### end Alembic commands ###
