"""increase statement length to 2000

Revision ID: b42494b3ff19
Revises: a085b9e13688
Create Date: 2026-04-23 19:09:19.823756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42494b3ff19'
down_revision: Union[str, Sequence[str], None] = 'a085b9e13688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_question_detail")
    op.alter_column('question', 'statement',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.execute(
        """
        CREATE VIEW v_question_detail AS
        SELECT
            q.id            AS question_id,
            q.statement,
            q.area,
            q.correct,
            q.alternative_a,
            q.alternative_b,
            q.alternative_c,
            q.alternative_d,
            q.tags,
            q.created_at,
            e.id            AS exam_id,
            e.name          AS exam_name,
            e.edition       AS exam_edition,
            e.year          AS exam_year,
            e.board         AS exam_board,
            e.first_phase_date,
            e.second_phase_date
        FROM question q
        JOIN exam e ON e.id = q.exam_id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_question_detail")
    op.alter_column('question', 'statement',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)
    op.execute(
        """
        CREATE VIEW v_question_detail AS
        SELECT
            q.id            AS question_id,
            q.statement,
            q.area,
            q.correct,
            q.alternative_a,
            q.alternative_b,
            q.alternative_c,
            q.alternative_d,
            q.tags,
            q.created_at,
            e.id            AS exam_id,
            e.name          AS exam_name,
            e.edition       AS exam_edition,
            e.year          AS exam_year,
            e.board         AS exam_board,
            e.first_phase_date,
            e.second_phase_date
        FROM question q
        JOIN exam e ON e.id = q.exam_id
        """
    )
    # ### end Alembic commands ###
