services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: foca-ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      JWT_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      JWT_ALGORITHM: "HS256"
      JWT_EXPIRE_MINUTES: 30

      LLM__TEMPERATURE: 0.7
      LLM__TIMEOUT: 30
      LLM__MAX_TOKENS: 1000
      LLM__MAX_RETRIES: 6
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: foca-ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
