services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: foca-ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
